### PR TITLE
feat: add missing derives for Algorithm

### PR DESCRIPTION
**Pull request by mmstick**
I require this for the following scenario, porting some C logic into Rust. It attempts to find the greatest possible checksum for an array of possible checksums, starting with SHA512 and gradually downgrading to SHA1.

```rust
const ALGORITHMS: &[Algorithm] = &[Algorithm::SHA512, Algorithm::SHA256, Algorithm::SHA1];

/// Based on libfwupd/fwupd-common.c
pub fn checksum_guess_kind(checksum: &str) -> Algorithm {
    match checksum.len() {
        32 => Algorithm::MD5,
        40 => Algorithm::SHA1,
        64 => Algorithm::SHA256,
        128 => Algorithm::SHA512,
        _ => Algorithm::SHA1,
    }
}

/// Find the best checksum available for an array of checksums.
pub fn find_best_checksum<S: AsRef<str>>(checksums: &[S]) -> Option<(&str, Algorithm)> {
    for &algorithm in ALGORITHMS {
        for checksum in checksums {
            if algorithm == checksum_guess_kind(checksum.as_ref()) {
                return Some((checksum.as_ref(), algorithm));
            }
        }
    }

    None
}
```

### CODE REVIEW

**Comment by malept** [comment]
Seems reasonable. I don't know why the coverage decreased, I'll need to find some time to look into that.

Adding derives is a non-breaking change, right?

**Comment by mmstick** [comment]
Indeed, adding derives only adds features, and does not modify any existing behavior. If you were not using these traits before, you won't be using them after.

**Comment by mmstick** [comment]
Any chance I could get this merged so I can publish https://github.com/pop-os/fwupd-dbus?

**Comment by malept** [comment]
I'll try to make some time this weekend to look into the coverage discrepancy.

**Comment by malept** [comment]
Thanks for your patience!

**Comment by malept** [comment]
Released in 0.3.4.

**Pull request merged**
